git add main.c;
git add main.h;
git add menu.c;
git add opening.c;
git add credits.c;
git add highscores.c;
git add logic.c;
git add logic.h;
git add imagehandler.c;
git add menu.h;
git add mk.sh;
git add opening.h;
git add options.c;
git add states.h;
git add images/game/enemy.png;
git add images/game/backgroundfull.png;
git add images/game/bullet.png;
git add images/gameover/win.png;
git add images/gameover/lose.png;
git add images/opening/sdlop.png;
git add images/menu/credits.png;
git add images/menu/highscores.png;
git add images/menu/menu.png;
git add images/menu/options.png;
git add images/game/boss.png;
git add images/game/down.png;
git add images/game/left.png;
git add images/game/medium.png;
git add images/game/pause.png;
git add images/game/playerw1.png;
git add images/game/playerw2.png;
git add images/game/playerw3.png;
git add images/game/right.png;
git add images/game/up.png;
git add images/opening/logo.png;
git add images/powerups/1.png;
git add images/powerups/2.png;
git add images/powerups/3.png;
git add images/powerups/damage.png;
git add images/powerups/life.png;
git add images/powerups/speed.png;
git add fonte.ttf;	
git add	images/game/historia.png;
git add	images/game/instructions.png;
git add	images/gameover/branco.png;
git add	images/gameover/preto.png;
git add	images/menu/roll.png;
git add	sounds/menu.mp3;
git add	sounds/boss.mp3;
git add	sounds/game.mp3;
git add	sounds/lose.mp3;
git add	sounds/win.mp3;
git add	images/game/boom.png;
git add	images/game/instructions1.png;
git add	images/menu/insertname.png;
git add	images/menu/options0.png;
git add	images/menu/options1.png;
git add	sounds/boss.wav;
git add	sounds/menu.wav;
git add	sounds/reload.wav;
git add gitadd.sh;
git add mk.sh;
git add	images/game/enemybullet.png;
git add	images/game/playerw1hurt.png;
git add	images/game/playerw2hurt.png;
git add	images/game/playerw3hurt.png;
git add	sounds/boom.wav;
git add	sounds/menuenter.wav;
git add	sounds/menuroll.wav;
git add INSTRUCOES.txt;
git add	images/game/playerw1dead.png;
git add	images/game/playerw2dead.png;
git add	images/game/playerw3dead.png;




git commit -m Automatic_Commit;
git push github master -f -v;


